### ISSUE TITLE
Could not get container for gitlab: No such container: gitlab

### ISSUE THREAD

**Issue by apelttom** [fialakarel/docker-nginx#1]
After running:
```
docker run \
>     --detach \
>     --restart always \
>     --name nginx \
>     --publish 80:80/tcp \
>     --publish 443:443/tcp \
>     --link gitlab:gitlab \
>     --volume /etc/localtime:/etc/localtime:ro \
>     --volume /etc/machine_id:/etc/machine_id:ro \
>     --volume /root/nginx/etc/nginx/sites:/etc/nginx/sites:ro \
>     --volume /root/nginx/etc/nginx/certs:/etc/nginx/certs:rw \
>     --volume /root/nginx/var/www/static.example.com:/var/www/static.example.com:ro \
>     fialakarel/nginx
```

I got an error:

```
docker: Error response from daemon: could not get container for gitlab: No such container: gitlab.
See 'docker run --help'.
```

Please what am I doing wrong? I follow the Production version of Readme

**Comment by fialakarel** [comment]
That's an example of possible usage. The problem is that you are trying to link `--link gitlab:gitlab` non-existing Docker container.

Please, see this Docker documentation.
https://docs.docker.com/network/links/#communication-across-links

Feel free to remove `--link gitlab:gitlab` in case you don't have such container running.

**Comment by apelttom** [comment]
True, true. Been digging around docker for a while and got it up and running on the simplest base:

```
docker build -t fiala-nginx .
docker run fiala-nginx
```
It probably doesn't do exactly what I want (like ports are not open so running a server in a docker with no open ports is at least a little funny :D) But it is a starting point.

Thanks for the reply. I guess I will fork and change the docker file to my liking.
You are da best!
